### PR TITLE
Added command line option to update the database then quit.

### PR DESCRIPTION
**Pull request by cs96and**
This adds a new command line option -u / --updatedb that updates the database and then quits. This allows the database to updated on e.g. a cron job.

Although the code change is pretty simple, I have never used GTK before so any feedback is welcome.

### CODE REVIEW

**Comment by cboxdoerfer** [comment]
Looks fine, thank you

**Comment by apapapapapapap** [comment]
Perfect, made my day. I love fsearch. Only the time-consuming update of the db every time i wanted to search for something was really annoying (takes about 5mins. here). Thanx.

**Comment by leodom** [comment]
Ahh ! Great, have been needing that for very long, I just love the program but got frustrated quite a few time by not being able to search when needed because of that loooooooong database update.
Keep spreading hapiness ! :)

**Comment by mag911** [comment]
Nice! Cheers heaps.

**Comment by leodom** [comment]
Was wondering :
When database is updating, it means long minutes without being able to search anything. 
- Could there be a mecanism to create/update a temporary database, and then switch it to be the regular one once it has finish reindexing ? (So search would still be available)
- Is there a system file or log or something implying a changed/new file on some folders that I coud use as a conditional flag to be able to test every _x_ minutes to decide if CRON should reindex or leave the database untouched ?
Thanks !

**Comment by AtilioA** [comment]
@cboxdoerfer is it possible to select database entries to be updated when using `-u`, à la #138? I got an HDD I'd rather rescan sporadically.

**Comment by cboxdoerfer** [comment]
Not yet, but I'm working on it.

**Pull request merged**
