### PR TITLE
Initial Brazilian Portuguese support lang addition

### PR DESCRIPTION
**Pull request by gustavohmsilva**
Please be advised that this file took as a base the Portuguese version (Portuguese as in from Portugal). It's important to point out that errors and missing links were found in the base language !

I'll try to solve that in my spare time, but I've barely spoke Portuguese (again, Portuguese as in from Portugal) since I was 12 years old. It is recommended that the original contributor, if a native speaker, to review the code.

### CODE REVIEW

**Comment by cboxdoerfer** [comment]
Cool, thank you :)

**Comment by gustavohmsilva** [comment]
You're welcome! I'll review everything soon and make a new revised commit after running the lang file in the actual running program.

**Comment by cboxdoerfer** [comment]
Thx, but for further translation please use Weblate: https://hosted.weblate.org/projects/fsearch/translations/

**Comment by gustavohmsilva** [comment]
There are some reasons why I prefer to use GitHub (I was aware of the translation tool) instead of Weblate. This kind of tools are always buggy when it comes to (ironically) translation... 
For example, in the Brazilian Portuguese, he keep pointing errors because of words that are equal to their english translations, and at least one error because they consider FSearch  as a word (which isn't the case, since the software name shouldn't be translated). Also, in Brazilian Portuguese, it is considered a language error to put every first letter of every word in uppercase, there are words that should be and words that shouldn't. I hope you understand my point. It is a wonderful tool for translators with no source code experience (since it's easy for them to break the code with some characters), but for people who understand the basic of coding, sometimes this tools are just a set back.

**Pull request merged**
