### PR TITLE
add missing dependency

### PR DESCRIPTION
**Pull request by Artturin**
im packaging fsearch for nixos and got a error while building because gio-unix-2.0 wasn't declared

### CODE REVIEW

**Comment by cboxdoerfer** [comment]
Thanks. But there's an issue with the autoconf build:

    > ./autogen.sh
    autopoint: using AM_GNU_GETTEXT_REQUIRE_VERSION instead of AM_GNU_GETTEXT_VERSION
    configure.ac:78: error: AC_SUBST: `GIO-UNIX_CFLAGS' is not a valid shell variable name
    ../../lib/autoconf/general.m4:1522: AC_ARG_VAR is expanded from...
    /usr/share/aclocal/pkg.m4:139: PKG_CHECK_MODULES is expanded from...  
    configure.ac:78: the top level

**Comment by Artturin** [comment]
could you make release/tags

**Comment by Artturin** [comment]
meson works but autoconf errors
```fsearch_window_actions.c:23:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
   23 | #include <gio/gdesktopappinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~```

**Comment by Artturin** [comment]
both meson and autoconf work now. i will be using meson in the package

**Comment by cboxdoerfer** [comment]
> could you make release/tags

Yes, I'll make a new beta release this weekend

**Comment by cboxdoerfer** [comment]
Looks good, merging. Thx!

**Comment by Artturin** [comment]
https://github.com/NixOS/nixpkgs/pull/127964

**Pull request merged**
