### PR TITLE
Restore Deleted Filesystem Entry Icon

### PR DESCRIPTION
**Pull request by bilgincoskun**
This patch fixes the regression of deleted file/folders still showing as normal.

### CODE REVIEW

**Comment by bilgincoskun** [comment]
Thanks for the feedback.  I thought  performance could be issue too but I tried on the database of  two large fully indexed HDDs   and did not notice any noticeable slowdown.  I can also do some benchmarks to be more accurate. Do icons generated during initial query or on demand? If it is the latter I think, it can be mitigated.

I think caching would defeat the purpose of this. Before regression I was using this feature to organize my files and live tracking which files are absent was very important. 

About symlinks, I think they can be fixed by changing access to lstat call. Incidentally stat also seems to be little more performant than  [https://stackoverflow.com/questions/12774207/fastest-way-to-check-if-a-file-exists-using-standard-c-c11-14-17-c](access) .

Like you said monitoring would be the best solution, but until then i think this kind of solution works well enough as a workaround.

**Comment by cboxdoerfer** [comment]
> I can also do some benchmarks to be more accurate.

That would be great.

> Do icons generated during initial query or on demand? If it is the latter I think, it can be mitigated.

Icons are generated on demand when the results are drawn on screen.

> I think caching would defeat the purpose of this. Before regression I was using this feature to organize my files and live tracking which files are absent was very important.

Well the time we keep the cache wouldn't need to be very long for significant performance gains. For example the cache could be refreshed every two seconds or so, so at most we'd get deleted files shown as existing ones for a few seconds.

> About symlinks, I think they can be fixed by changing access to lstat call. Incidentally stat also seems to be little more performant than [https://stackoverflow.com/questions/12774207/fastest-way-to-check-if-a-file-exists-using-standard-c-c11-14-17-c](https://github.com/cboxdoerfer/fsearch/pull/access) .

That sounds good.

> Like you said monitoring would be the best solution, but until then i think this kind of solution works well enough as a workaround.

Yes, I think it's ok to add a non-optimal workaround for the time being.

**Comment by bilgincoskun** [comment]
Ok, lstat solved the symlink issue. Unfortunately it is not compliant with c11 and requires gnu11 or at least explicitly defining some macros otherwise although it works correctly it gives implicit definition [warning.](https://stackoverflow.com/questions/22851629/compiler-doesnt-recognize-lstat-even-with-the-includes). Is this a problem?

I tried to benchmark the PR by only calculating the average time required by get_icon_surface by searching about 1 million files traversing the result list randomly using  regex '.' on an external HDD but it varies greatly. It seems stat is cached by the kernel already so if the filesystem is already used it seems overhead seems to be small. Searching on sleeping or newly mounted HDD on the other hand, introduces a visible lag for the first uses, although it gradually disappears.  Note that if the filesystem is unmounted already, there is no lag introduced by lstat. So I am not sure if it is an acceptable trade-off.

**Comment by cboxdoerfer** [comment]
> Ok, lstat solved the symlink issue. Unfortunately it is not compliant with c11 and requires gnu11 or at least explicitly defining some macros, otherwise, although it works correctly it gives implicit definition [warning.](https://stackoverflow.com/questions/22851629/compiler-doesnt-recognize-lstat-even-with-the-includes). Is this a problem?

The warning about the implicit definition is because `#define _GNU_SOURCE` is missing at the top of the c file.

We can fix this globally by passing `-D_GNU_SOURCE` to the compiler, then we won't need those `#define`'s spread throughout the code. But that should be done separately to this PR.

> I tried to benchmark the PR by only calculating the average time required by get_icon_surface by searching about 1 million files traversing the result list randomly using regex '.' on an external HDD but it varies greatly. It seems stat is cached by the kernel already so if the filesystem is already used it seems overhead seems to be small. Searching on sleeping or newly mounted HDD on the other hand, introduces a visible lag for the first uses, although it gradually disappears. Note that if the filesystem is unmounted already, there is no lag introduced by lstat. So I am not sure if it is an acceptable trade-off.

Yes, that's what I thought. When the kernel already has the files cached, it's barely noticeable, otherwise it'll block while the disk accesses the file. 

Ideally all code paths which access the filesystem (getting the icons and content type, testing for file existence, ...) should be non-blocking. Is this something you'd be interested/willing to try out? This would be more complex to implement. It would probably look something like that:

* The main thread (responsible for drawing) feeds a queue with IO requests for files which need to be drawn.
* A different thread monitors that queue and works through all those IO requests, triggering a callback with the result, which then causes the view to redraw with the correct data.
* IO requests for files which scrolled out of view should get cancelled.

**Comment by bilgincoskun** [comment]
Coincidentally, while checking the code before regression, found  g_file_query_info_async which might be useful.  But like you said it is a much more complex task and It will take some time to implement for me due to other stuff. And since ultimately it will be superseded by file monitoring, I am not sure it is worth as a short-term solution.

**Comment by cboxdoerfer** [comment]
> Coincidentally, while checking the code before regression, found g_file_query_info_async which might be useful.

The problem with that is that each call spawns its own thread. So we will end up spawning dozens of threads (which all fight for IO access) every time the list gets drawn. It's better to have one separate IO thread, which waits for requests from the main thread and calls `g_file_query_info`. This way only one IO operation will be performed at a time, the IO thread can stay alive all the time and the main thread won't block.

> But like you said it is a much more complex task and It will take some time to implement for me due to other stuff. And since ultimately it will be superseded by file monitoring, I am not sure it is worth as a short-term solution.

The async IO handling needs to be implemented either way and will coexist with the file monitoring. Because for example we still need to load the icons for drawing, or access the filesystem for data which isn't indexed (like the content type).

If that's something you'd be interested in implementing, just let me know and I'll try to help. Otherwise I'd implement it myself in a couple of weeks or months probably.

In the meantime, I guess it's fine to use the blocking `lstat` solution as a workaround. Because it does provide useful information to the user. So I think the only thing missing to get this PR merged is the `#define _GNU_SOURCE` at the top of the C file to get rid of the implicit definition warning.

**Comment by bilgincoskun** [comment]
> In the meantime, I guess it's fine to use the blocking lstat solution as a workaround. Because it does provide useful information to the user. So I think the only thing missing to get this PR merged is the #define _GNU_SOURCE at the top of the C file to get rid of the implicit definition warning.

Ok I added the line.

> The async IO handling needs to be implemented either way and will coexist with the file monitoring. Because for example we still need to load the icons for drawing, or access the filesystem for data which isn't indexed (like the content type).
>
>If that's something you'd be interested in implementing, just let me know and I'll try to help. Otherwise I'd implement it myself in a couple of weeks or months probably.

If that is the case, I certainly would like to give it a try.

**Comment by cboxdoerfer** [comment]
> Ok I added the line.

Great, merged.

> If that is the case, I certainly would like to give it a try.

That's cool. Just let me know when you have any questions.

**Comment by bilgincoskun** [comment]
> That's cool. Just let me know when you have any questions.

Will do, thanks

**Pull request merged**
