### PR TITLE
Added option to report file sizes in base 2 units

### PR DESCRIPTION
**Pull request by torbei**
it's disabled by default but you can change it in the settings

Solves Issue #61

### CODE REVIEW

**Comment by cboxdoerfer** [comment]
Thanks. Looks fine.

**Comment by torbei** [comment]
You could argue if it should be enabled by default or not.
But at least there is choice now

**Comment by cboxdoerfer** [comment]
Yes, personally I prefer base-10 for file sizes, but I don't have a strong opinion about that. So if you want to change the default to base-2 feel free to do it.

**Comment by torbei** [comment]
I don't have any strong argument about either. So it's fine like that

**Pull request merged**
