### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ferambot**
Hi, I am Feram,

I'm a bot and I work on behalf of [Adrian][adius].
If my merge request helped to improve this repository,
please consider to [star my repo][repo] to show some love! 😊

If I didn't behave, you can [create an issue][issues]
and my dad will try to fix me.

Love, hugs and kisses,
your [Feram][feram]

[adius]: https://github.com/adius
[feram]: https://github.com/ferambot
[repo]: https://github.com/ferambot/feram
[issues]: https://github.com/ferambot/feram/issues

### CODE REVIEW

**Comment by cboxdoerfer** [comment]
Merged. Thx, little bot. And greetings to your master.

**Comment by adius** [comment]
Thanks for the greetings and greetings back! 😊

I'm just a little confused: It says "closed" and not "merged"
and the original commits are not  in the history,
but a merge commit is.
How exactly did that happen? ^^

**Comment by cboxdoerfer** [comment]
Hi, I had to manually merge it due to a minor merge conflict - I deleted a file your bots commit was modifying. Apparently github didn't detect that so I had to manually close the PR. Commit is here: https://github.com/cboxdoerfer/fsearch/commit/c3c110887c0ba876eb56e6ab6d4887942df3ea13

**Comment by adius** [comment]
Ah OK, makes sense. Thanks for your feedback!

(Just for completeness sake: Normally you should have added an additional commit to the pull-request branch
to fix the problem and then merge it. This would have ensured that Feram
gets proper credit for his contribution. Luckily he's a bot and very forgiving 😂,
but I know folks who would have been fed up for not getting the proper recognition for their help…)

**Comment by cboxdoerfer** [comment]
Yes, good point. I will bear that in mind next time.

**Pull request closed without merging**
